pipeline {
    agent any

    tools {
        maven 'Maven 3.9.6' // Make sure Jenkins has Maven installed and named exactly this
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/srikant-h/CICD-login.git'
            }
        }

        stage('Build with Docker') {
            steps {
                script {
                    dockerImage = docker.build("selenium-login-ci")
                }
            }
        }

        stage('Run Tests inside Docker') {
            steps {
                script {
                    dockerImage.inside('--shm-size=1g') {
                        sh 'mvn test'
                    }
                }
            }
        }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
        }
    }
}

