pipeline {
    agent any

    tools {
        maven 'Maven 3.9.6'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/srikant-h/CICD-login.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("selenium-login-ci")
                }
            }
        }

        stage('Run Tests in Docker') {
            steps {
                script {
                    dockerImage.inside('--shm-size=1g') {
                        sh 'mvn -B test'
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Publishing test results..."
            junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'
        }
    }
}
